###
POST http://localhost:8080/api/v1/book/add
Content-Type: application/json

{
  "title":"sfBooks",
  "autor":4,
  "category":3,
  "publicationDate":2022
}
###
POST http://localhost:8080/api/v1/book/add
Content-Type: application/json

{
"title":"",
"autor":0,
"category":0,
"publicationDate":2024
}

###
GET http://localhost:8080/api/v1/book/1

###
GET http://localhost:8080/api/v1/book


